### ISSUE TITLE
Text editor in 'insert' tab not working; unable to insert new documents

### ISSUE THREAD

**Issue by bartpype** [garraflavatra/rolens#26] opened 2023-06-05 15:11 UTC
### Bug description

Could not insert new text in 'insert' panel.

### Reproduction

Open a host and collection. Click on 'insert' tab and try to enter JSON formatted data

### Version

0.2

### Environment information

```shell
Intel Mac, MacOS 11.7.4
```

### Severity of this bug

Blocking a specific feature

**Comment by garraflavatra** [comment] 2023-06-05 19:48
Thanks for reporting the issue. Do you mean you are unable to enter any text into the editor in the insert panel? I cannot reproduce it on macOS 13.2.1 (ARM).

**Comment by garraflavatra** [comment] 2023-06-07 19:55
Ok, does the logfile (_Rolens > Open log directory… > `rolens.log`_) report something about unhandled JavaScript exceptions?

**Comment by garraflavatra** [comment] 2023-06-07 20:03
That's odd… 

The delete panel has the same JSON editor; does it allow you to insert text there? And in the editor in the the aggregate tab?

**Comment by bartpype** [comment] 2023-06-07 20:05
Hadn’t tested those…

But no input allowed in any of those three editor panels. (Input/remove/aggregate)

**Comment by garraflavatra** [comment] 2023-06-07 20:23
I really cannot reproduce it on neither macOS 13, Fedora 36, nor Windows 11 ARM. Therefore this issue could be caused by either macOS 11.7, or the AMD processor. 

I'll test on an AMD Mac tomorrow.

**Comment by garraflavatra** [comment] 2023-06-21 18:24
Nothing odd to see on an ARM machine running macOS 13…

Is the following (except text) exactly the text editor you see?

![image](https://github.com/garraflavatra/rolens/assets/34036573/2719cea9-8023-45bc-9ea3-351bf434542e)

**Comment by garraflavatra** [comment] 2023-06-21 18:24
Sorry, I ment AMD.

**Comment by garraflavatra** [comment] 2023-07-04 16:22
As we discussed, it started working after you upgraded to macOS 13. I'll close this ticket for now. Please feel free to re-open it or file a new issue whenever this problem shows up again.

Thanks!

**Closed** 2023-07-04 16:22 UTC
Labels: bug, prio: high
